version: "3.9"

services:
  app:
    build: .
    container_name: ctf1-basic-nodejs
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./flags.json:/app/flags.json:ro
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped
