// src/controllers/flagController.js
const { getFlag } = require('../services/flagService');

function getFlagController(req, res) {
  // 1) Not logged in at all → redirect to login
  if (!req.user) {
    return res.redirect('/');
  }

  // 2) Logged in but not admin → show "Admins only" page (styled)
  if (req.user.role !== 'admin') {
    return res.status(403).send(`
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>CTF-1 – Admins only</title>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
          <link rel="stylesheet" href="/css/custom.css">
        </head>
        <body class="bg-light">
          <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
              <a class="navbar-brand d-flex align-items-center" href="#">
                <span class="logo-box me-2"></span>
                <span class="brand-text">CTF-1</span>
              </a>
            </div>
          </nav>
          <main class="container py-5">
            <div class="row justify-content-center">
              <div class="col-md-8">
                <div class="card shadow-sm border-danger">
                  <div class="card-body">
                    <h3 class="card-title text-danger">Admins only</h3>
                    <p>You found the admin area, but you're not an admin yet.</p>
                    <div class="alert alert-info" role="alert">
                      Hint: how does the site remember who you are? Can that be modified?
                    </div>
                    <p><a class="btn btn-primary" href="/home">Back to home</a></p>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </body>
      </html>
    `);
  }

    // 3) Logged in as admin → show per-user flag
    const username = req.user.username;
    const flag = getFlagForUser(username);

    if (!flag) {
      return res.status(500).send(`
        <!doctype html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>CTF-1 – Flag</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
            <link rel="stylesheet" href="/css/custom.css">
          </head>
          <body class="bg-light">
            <nav class="navbar navbar-expand-lg navbar-dark">
              <div class="container">
                <a class="navbar-brand d-flex align-items-center" href="#">
                  <span class="logo-box me-2"></span>
                  <span class="brand-text">CTF-1</span>
                </a>
              </div>
            </nav>
            <main class="container py-5">
              <div class="row justify-content-center">
                <div class="col-md-8">
                  <div class="card shadow-sm">
                    <div class="card-body">
                      <h3 class="card-title">Flag not configured</h3>
                      <p>No flag found for user <strong>${username}</strong>.</p>
                      <p>In a real deployment this would be generated by the challenge-generation tooling.</p>
                      <p><a class="btn btn-primary" href="/home">Back to home</a></p>
                    </div>
                  </div>
                </div>
              </div>
            </main>
          </body>
        </html>
      `);
    }

    return res.send(`
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>CTF-1 – Flag</title>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
          <link rel="stylesheet" href="/css/custom.css">
        </head>
        <body class="bg-light">
          <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
              <a class="navbar-brand d-flex align-items-center" href="#">
                <span class="logo-box me-2"></span>
                <span class="brand-text">CTF-1</span>
              </a>
              <div class="d-flex">
                <a class="btn btn-outline-light btn-sm me-2" href="/home">Home</a>
                <a class="btn btn-outline-light btn-sm" href="/logout">Logout</a>
              </div>
            </div>
          </nav>

          <main class="container py-5">
            <div class="row justify-content-center">
              <div class="col-md-8">
                <div class="card shadow-sm">
                  <div class="card-body">
                    <h3 class="card-title">Congratulations, ${username}!</h3>
                    <p class="mb-3">You have admin access.</p>
                    <p class="mb-1">Your flag is:</p>
                    <div class="d-flex align-items-start gap-2">
                      <pre class="flag-box mb-0 flex-grow-1" id="flagText">${flag}</pre>
                      <div>
                        <button id="copyBtn" class="btn btn-outline-primary" title="Copy flag">Copy</button>
                      </div>
                    </div>
                    <p class="text-muted mt-3">For your dissertation: this demonstrates a privilege escalation via insecure cookies / login logic.</p>
                  </div>
                </div>
              </div>
            </div>
          </main>

          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
          <script>
            // Copy-to-clipboard for the flag
            document.addEventListener('DOMContentLoaded', function () {
              const copyBtn = document.getElementById('copyBtn');
              const flagEl = document.getElementById('flagText');
              if (!copyBtn || !flagEl) return;

              copyBtn.addEventListener('click', async function () {
                try {
                  // Use innerText to avoid extra whitespace
                  await navigator.clipboard.writeText(flagEl.innerText.trim());
                  // temporary feedback
                  const original = copyBtn.innerText;
                  copyBtn.innerText = 'Copied!';
                  copyBtn.disabled = true;
                  setTimeout(() => { copyBtn.innerText = original; copyBtn.disabled = false; }, 1500);
                } catch (err) {
                  alert('Copy failed: ' + err);
                }
              });
            });
          </script>
        </body>
      </html>
    `);
  return res.send(`
    <h1>Congratulations, ${req.user.username}!</h1>
    <p>You have admin access.</p>
    <p>Your flag is:</p>
    <pre>${flag}</pre>
    <p>For your dissertation: this demonstrates a privilege escalation via insecure cookies / login logic.</p>
  `);
}

module.exports = {
  getFlag: getFlagController
};
